### ISSUE TITLE
Strange behaviour with button touch on mobile devices

### ISSUE THREAD

**Issue by joepadmiraal** [openhab/smarthome.paperui#6] opened 2015-07-17 20:02 UTC
When clicking on a button on a laptop the button slides on, or off.
When touching a button on a Samsung galaxy S5 or Nexus 7 the button stays off.
It seems like the button on and off action are both done twice:

    2015-07-17 21:59:08.111 [INFO ] [runtime.busevents             ] - DenonPower received command ON 
    2015-07-17 21:59:08.194 [INFO ] [runtime.busevents             ] - DenonPower state updated to OFF
    2015-07-17 21:59:08.793 [INFO ] [runtime.busevents             ] - DenonPower state updated to ON
    2015-07-17 21:59:14.926 [INFO ] [runtime.busevents             ] - DenonPower received command OFF

When sliding the button it does work like expected.
So the ON or OFF event is only sended once.

**Comment by dnobel** [comment] 2015-07-20 08:53
OK, will check that.

**Comment by dnobel** [comment] 2015-07-24 14:04
Sorry for late response. I can confirm the issue. A lot of thel Material Design elements are not working (switches, check boxes). As you say they are always triggered twice. Have to investigate it, if it´s something within the library or in the Paper UI.

**Comment by joepadmiraal** [comment] 2015-08-10 19:04
I did some digging around.
Upgrading angular-material to 0.9.0 or higher fixes the issue.
That however messes up the css.

To fix this both paper-ui and openhab needs to be changed.
I can try to fix the css issues and create a pull request for both projects.

**Comment by dnobel** [comment] 2015-08-10 19:37
An update to angular-matrial 0.9.0 was already on my list, but I did´t had the time. On my first check I also saw some css problems, as well as icon sizes. I think in addition dialogs were not working properly.

But you can give it try and create a PR if you got it working.

Is an update for openHAB2 really needed? There are only few css color changes.

**Comment by dnobel** [comment] 2015-08-10 19:39
Sorry, we need to update to 0.10.0. Kai created the CQ for this version (see #3).

**Comment by joepadmiraal** [comment] 2015-08-11 06:09
The theme.css file from org.openhab.ui.paperui contains css for md-tab.
md-tab seems to be renamed to md-tab-item so that's why I think we also need to update openHAB2.

I got the tab's working except for the white underline for the active tab.
I'll do some research to see if more elements are renamed in angular-material.

**Comment by dnobel** [comment] 2015-09-02 16:31
Do you have any news regarding the update of angular-material?

**Comment by joepadmiraal** [comment] 2015-09-03 07:03
Sorry for the delay, it is more work than I expected.
I have most things looking like in the old version.
I try to do a push to my repo tonight so you can see the changes.

**Comment by joepadmiraal** [comment] 2015-09-03 14:53
I committed my changes in my repo: https://github.com/joepadmiraal/smarthome.paperui/tree/angular-material-0.10.1

I changed the tabs in control.html to be more in line with the example from angular material. This makes the taps slide when when switch tabs which is a nice effect. Also my first attempt to position all elements correctly without changing the html did not work.
However it also makes switching tabs a lot slower.
I'm not sure what is causing this so any help on this issue would be great.

**Comment by dnobel** [comment] 2015-09-03 21:44
Thanks, will try to test that tomorrow.

**Comment by dnobel** [comment] 2015-09-03 22:13
> However it also makes switching tabs a lot slower.

I think this is just the animation. Or is it so slow for you? I have added around 30 items and it switches within half a second. But a problem with this approach is, that all items of all groups are rendered at once. Before only the items of the visible tabs were rendered. So the initial load time of the control section is longer.

Besides that I still see a lot of positioning problems in several views. Looks like the css of angular-material has changed a lot.

**Comment by joepadmiraal** [comment] 2015-09-04 05:39
I can imagine initial load time being higher. However on my mac pro it takes 4 seconds before the animation starts after clicking on a tab.

Can you send a screenshot of the positioning problems?
I wonder whether I did not see them or if it is something I missed in the commit.

**Comment by dnobel** [comment] 2015-09-07 06:12
Sorry for late response. I created a new issue for the update of the Paper UI: #22 . Is this issue actually fixed by the update?

**Comment by joepadmiraal** [comment] 2015-09-07 08:35
Yes when using the newer version of angular-material the buttons work great on mobile devices.
Since the work is going on in ticket #22 we can close this ticket right?

**Comment by dnobel** [comment] 2015-09-28 18:06
Now we can close it, as the new version of Angular Material fixes the problem. Thanks again!

**Closed by dnobel** 2015-09-28 18:06 UTC
